### ISSUE TITLE
Aumentar a capacidade de inserção de texto nas box de descrição

### ISSUE THREAD

**Issue by 648trindade** [capmayer/catalogo_project#1]
O sistema atual permite somente 255 caracteres tanto pra descrição de recurso quanto pra de feedback, o que pode ser muito pouco (menos de dois tweets)

Se for pra manter um limite, recomendo expandir pra 500.

**Comment by capmayer** [comment]
Olá, @648trindade! Realmente 255 caracteres é pouco, vou aumentar!

**Comment by capmayer** [comment]
Feito!
