### ISSUE TITLE
Feedbacks só exibem o título

### ISSUE THREAD

**Issue by 648trindade** [capmayer/catalogo_project#2]
O título da issue explica por si só. As descrições do feedback e o nome do usuário não são exibidos.

**Comment by capmayer** [comment]
Olá, @648trindade! A principio é para mostrar apenas o título, pois estamos pensando uma forma mais elegante de mostrar os feedbacks. Logo mais será implementado. Obrigado pela colaboração.

**Comment by capmayer** [comment]
Implementado.
